version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - STRIPE_TEST_PUBLISHABLE_KEY=${STRIPE_TEST_PUBLISHABLE_KEY}
      - STRIPE_TEST_SECRET_KEY=${STRIPE_TEST_SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
